import { useCallback, useEffect, useState } from 'react'
import { Button } from '@/components/ui/Button'
import { Markdown } from '@/components/ui/Markdown'
import { Modal } from '@/components/ui/Modal'
import { SparkleIcon } from '@/components/ui/icons'
import { ApiError } from '@/lib/api'
import { formatRelativeTime } from '@/lib/format'
import { getSummary, requestSummary } from '@/services/documentService'
import type { DocumentSummary, ResearchDocument } from '@/types/research'

const POLL_INTERVAL_MS = 2000

/**
 * Shows a document's AI summary. If there is none yet it offers to generate
 * one, then polls while the backend works (usually 10–60 s on a local model).
 */
export function SummaryModal({
  document,
  onClose,
}: {
  document: ResearchDocument | null
  onClose: () => void
}) {
  const [summary, setSummary] = useState<DocumentSummary | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const projectId = document?.projectId
  const documentId = document?.id

  // Load whatever exists when the modal opens.
  useEffect(() => {
    if (!projectId || !documentId) return
    let cancelled = false
    setSummary(null)
    setError(null)
    setIsLoading(true)
    getSummary(projectId, documentId)
      .then((result) => {
        if (!cancelled) setSummary(result)
      })
      .catch((caught: unknown) => {
        if (!cancelled) setError(caught instanceof ApiError ? caught.message : 'Could not load')
      })
      .finally(() => {
        if (!cancelled) setIsLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [projectId, documentId])

  // Poll while the summary is being generated.
  const isGenerating = summary?.status === 'processing'
  useEffect(() => {
    if (!isGenerating || !projectId || !documentId) return
    const timer = window.setInterval(() => {
      getSummary(projectId, documentId)
        .then((result) => result && setSummary(result))
        .catch(() => undefined)
    }, POLL_INTERVAL_MS)
    return () => window.clearInterval(timer)
  }, [isGenerating, projectId, documentId])

  const generate = useCallback(async () => {
    if (!projectId || !documentId) return
    setError(null)
    try {
      setSummary(await requestSummary(projectId, documentId))
    } catch (caught) {
      setError(caught instanceof ApiError ? caught.message : 'Could not start the summary')
    }
  }, [projectId, documentId])

  const canGenerate = !isLoading && !isGenerating
  const hasSummary = summary !== null

  return (
    <Modal
      open={document !== null}
      onClose={onClose}
      title="Document summary"
      description={document?.name}
      footer={
        <>
          <Button variant="ghost" onClick={onClose}>
            Close
          </Button>
          <Button onClick={() => void generate()} disabled={!canGenerate}>
            <SparkleIcon className="size-4" />
            {isGenerating ? 'Generating…' : hasSummary ? 'Regenerate' : 'Generate summary'}
          </Button>
        </>
      }
    >
      {isLoading ? (
        <p className="text-[0.84rem] text-ink-500">Loading…</p>
      ) : error ? (
        <p role="alert" className="rounded-xl bg-red-50 px-3 py-2.5 text-[0.8rem] text-red-700">
          {error}
        </p>
      ) : !summary ? (
        <p className="text-[0.84rem] leading-6 text-ink-600">
          No summary yet. Generate one to get an overview and the key points of this document,
          written by the local AI model from the document's text only.
        </p>
      ) : summary.status === 'processing' ? (
        <div className="flex items-center gap-3 text-[0.84rem] text-ink-600">
          <span
            className="size-2 rounded-full bg-amber-500"
            style={{ animation: 'pulse-dot 1.4s ease-in-out infinite' }}
          />
          Summarising… this usually takes 10–60 seconds on the local model.
        </div>
      ) : summary.status === 'failed' ? (
        <p role="alert" className="rounded-xl bg-red-50 px-3 py-2.5 text-[0.8rem] text-red-700">
          {summary.error ?? 'Summarising failed.'}
        </p>
      ) : (
        <div>
          <div className="text-[0.86rem] leading-7 text-ink-700">
            <Markdown content={summary.content ?? ''} />
          </div>
          <p className="mt-4 border-t border-ink-100 pt-3 text-[0.72rem] text-ink-400">
            Generated by {summary.model ?? 'the local model'}
            {summary.completedAt ? ` · ${formatRelativeTime(summary.completedAt)}` : ''} · AI
            summaries can contain mistakes; check important points against the document.
          </p>
        </div>
      )}
    </Modal>
  )
}
